### ISSUE TITLE
Test + Code Refactor + Docs

### ISSUE THREAD

**Issue by daniel4x** [daniel4x/Assignment1#6]
**TODO:**

- [x] Code Refactor.
- [x] Generate graphs & queries for test.
- [x] Triangle inequality tests.
- [x] Performance test -> instead of clone graph, remove nodes and add them back.

**Comment by daniel4x** [comment]
Done refactor + Docs, Please re-clone the project and write tests.
